services:
#    blog_blog.example:
#        class: Blog\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    blog_blog.nbr_pages:
        class: Blog\BlogBundle\Services\nbrPages